[package]
name = "nyaa-rsearch"
version = "0.1.0"
edition = "2021"
description = "A rust library for search Torrent on nyaa.si"
license = "MIT"

[dependencies]
reqwest = { version = "0.11.18", features = ["blocking"] }
scraper = "0.17.1"
